ARGOeu/argo-compute-engine

status-computation/java/src/main/java/ar/EndpointTimelines.java, status-computation/java/src/main/java/ar/MetricTimelines.java, status-computation/java/src/main/java/ar/PickEndpoints.java, status-computation/java/src/main/java/ops/DAggregator.java, status-computation/java/src/main/java/ops/DIntegrator.java, status-computation/java/src/main/java/ops/DTimeline.java, status-computation/java/src/main/java/ops/OpsManager.java, status-computation/java/src/main/java/sync/AvailabilityProfiles.java, status-computation/java/src/test/java/ops/DAggregatorTest.java, status-computation/java/src/test/java/sync/AvailabilityProfilesTest.java, status-computation/java/src/test/resources/ops/EGI-ar.json, status-computation/java/src/test/resources/ops/ap1.json, status-computation/pig/compute-ar.pig
Availability profiles can now be supplied in json file form along with the other sync files.
the .json file also includes definitions of operations to take place between instances of the same service type (for eg. ORing , or ANDing or FOOing between  a site's CREAM-CE's).
=> Standalone - Support Availability Profiles served as sync files

ar-compute.spec, conf/ar-compute-engine.conf
Scripts ran successfully on devel. The only thing found was a typo in the ar-compute-engine.conf
Please merge
=> Config file fix typo

bin/argolog.py, bin/argorun.py
The logging format has been slightly changed and process id has been added to be better conformed with the format expected by log parsers (logstash,splunk etc)
before:
timestamp  [process_name] level message
after:
timestamp  process_name[proc_id]:  level  message  
The change was implemented to the python logging formaters (both for the two handlers: file / syslog)
=> add process_id to logging to be better conformed for log parsers

bin/job_cycle.py, conf/ar-compute-engine.conf
Setting of five environment variables from within job_cycle.py script, so that tools the CE uses log properly to some log files what is going one per computation.
=> ARGO-45 Configuration of pig and hadoop clients logging from within CE

ar-compute.spec
I need to test new VO sync component, but as name has changed I realized it (the sync components package) cannot be updated on our nodes as there was an rpm runtime dependency. This commit removes this dependency.
=> ARGO-61 Removed runtime dependency on ar-sync package

bin/job_cycle.py, bin/job_status_detail.py, bin/sync_backup.py, conf/ar-compute-engine.conf
Derived from ARGO-67 Issue
Derived from work on documenting argo-engine configuration (https://github.com/ARGOeu/argodoc/pull/5):
In multi-tenant enviroments there is the need to configure a list of available tenants
and also for each tenant a list of jobs. 
Right now ar-compute engine conf there is the following section:
[jobs]
tenant=tenantA 
job_set=job1,job2 etc...
With this patch the .conf declaration changes to:
[jobs]
tenants=tenantA,tenantB
tenantA_jobs=job1,job2,job3
tenantB_jobs=job4,job5
which is needed in multi-tenant enviroments and gives a better understanding to the end-user on what is actually configured.
If accepted it will be reflected in the documentation also
=> Better tenant/job declaration in conf file (multitenant enviroments)

bin/upload_metric.py
I accidentally noticed something in a previous commit of mine. This fixes it I think:
* use the short `args.tenant` instead of the longer `arg_parser.parse_args().tenant`
=> Minor fixes

ar-compute.spec, bin/argolog.py, bin/job_ar.py, bin/job_cycle.py, bin/job_status_detail.py, bin/mongo_clean_ar.py, bin/mongo_clean_status.py, bin/sync_backup.py, bin/test_argolog.py, bin/upload_metric.py, bin/upload_sync.py
The default value for log_file in the python scripts was 'none' (type string) so when no log_file was set, a new log_file was created with the name 'none'.
Changed default values to None and added assertion when initializing the logger
=> ARGO-125 Changed 'none' to None for log_file name

ar-compute.spec, bin/mongo_recompute.py, bin/upload_sync.py, bin/utils.py, bin/utils_test.py
There was a deprecated reference to the argo-connector path (arsync, now it's argo-connectors).
The reference is now retrieved from the configuration file 
please review 
/cc @pkoro
=> ARGO-129 - bugfix - Argo connector path reference fix (in recomputation scripts)

bin/job_ar.py, bin/job_status_detail.py, bin/utils.py, bin/utils_test.py, conf/ar-compute-engine.conf, status-computation/java/src/main/java/ar/GroupEndpointMap.java, status-computation/java/src/main/java/ar/ServiceMap.java, status-computation/java/src/main/java/status/PrepStatusDetails.java, status-computation/pig/compute-ar.pig, status-computation/pig/compute-status.pig
- In this request the UDFs that prepare the data for output (such as GroupEndpointMap and ServiceMap) have been updated
- Specifically the output tuple of the eval functions has been aligned with the fields expected in the mongodb schema
- Accordingly the field names have been changed in the ouputSchema function of the udf
- Changes have been reflected also in the pig scripts. Alignment has been establish right before mongo_pig_connector writes the results to the datastore
- Same changes for the status details 
- Since now the fields have standard generic full blown names the mapping functionality (name->abbr) have been dropped from the code and from the configuration files
=> ARGO-155 Align CE output fields with new mongodb schema

.travis.yml, README.md, ar-compute.spec, bin/job_ar.py, bin/mongo_clean_ar.py, bin/mongo_clean_status.py, bin/utils.py, bin/utils_test.py, status-computation/java/src/main/java/ar/GroupEndpointMap.java, status-computation/java/src/main/java/ar/ServiceMap.java, status-computation/java/src/main/java/ops/ConfigManager.java, status-computation/java/src/test/java/ops/ConfigManagerTest.java, status-computation/pig/compute-ar.pig
- In the new multitenant schema report's name as a field plays a critical role in partitioning and indexing the results. 
- The report field is exposed in the udfs that prepare data before outputting to mongo (such as GroupEndpointMap and ServiceMap). 
- Pig scripts are changed accordingly to incorporate the newly exposed field from the udfs
- Python scripts that are used for mongo cleanup are updated to use the new report field
- unit tests added
=> ARGO-156 Expose report name field

ar-compute.spec
The two offending files were:
- /usr/libexec/ar-compute/ar-compute.pyc
- /usr/libexec/ar-compute/ar-compute.pyo
=> Adds missing pyc and pyo files

status-computation/java/pom.xml, status-computation/java/src/main/java/status/PrepStatusDetails.java, status-computation/java/src/test/java/sync/AvailabilityProfilesTest.java, status-computation/java/src/test/java/sync/MetricProfilesTest.java, status-computation/pig/compute-status.pig
The xml response for status metric results needs to include the endpoint group name. The status metric collection in the datastore doesn't contain an endpoint group name field (has been omitted by mistake). This fix intends to expose the field again in the output of the compute engine.
=> ARGO-211 - Add Endpoint group field output

bin/mongo_recompute.py, bin/mongo_recompute_test.py, bin/poller_ar.py, bin/recompute.py, bin/recompute_test.py, bin/test_poller_ar.py, bin/upload_sync.py, bin/utils.py, bin/utils_test.py, status-computation/java/src/main/java/ar/GroupEndpointIntegrate.java, status-computation/java/src/main/java/ar/GroupEndpointMap.java, status-computation/java/src/main/java/ar/GroupEndpointTimelines.java, status-computation/java/src/main/java/ar/ServiceIntegrate.java, status-computation/java/src/main/java/ar/ServiceMap.java, status-computation/java/src/main/java/sync/Recomputations.java, status-computation/java/src/test/java/sync/RecomputationsTest.java, status-computation/java/src/test/resources/ops/recomp.json
- Change some udf schema defs for future compatibility with CDH 5.x and pig 12
- Change recomputation handling in CE (remove use of supergroups)
- Change python scripts
- retrieve recomputation by uuid (instead of object _id)
- use report names when executing recomputations
=> ARGO-247 Recomputation apiv2 profile changes

ar-compute.spec
After upgrading cluster to CDH 5.x, java 1.7 is required. 
Change spec file requirement to openjdk-1.7.0
=> ARGO-245 Update Spec requirement for java-1.7.0-openjdk

ar-compute.spec
Remove hcatalog requirement (After Upgrading cluster to CDH 5.x)
=> ARGO-245 Update Spec remove hcatalog requirement

status-computation/java/src/main/java/ar/GroupEndpointMap.java, status-computation/java/src/main/java/ar/ServiceMap.java, status-computation/java/src/main/java/ops/ConfigManager.java, status-computation/java/src/main/java/status/PrepStatusDetails.java, status-computation/java/src/test/java/ops/ConfigManagerTest.java, status-computation/java/src/test/resources/ops/config.json~
Each defined report in the Compute Engine is used to produce a different set of results. The results while produced and stored in datastore are tagged with the according report name for future reference.
In this PR, the Compute Engine uses the report's id (uuid) as a future reference and tags the results. This gives the flexibility to be able to update/edit report.name field without affecting the relationship with the already computed results
- Report information is loaded through configuration in the ConfigManager Class. Class has been updated to hold a new field `id` regarding report.id. Also the json Load function has been updated to look for an `id` field in json configuration.
- Java UDFS regarding a/r and status results have been updated to use ConfigManager.id field as a report …
=> ARGO-245 Reference results using report.id instead of report.name

bin/job_ar.py, bin/job_status_detail.py, doc/cli-interaction.md
Mongo clean data scripts still target results using report name. Should use report id
Use report id when calling clean scripts mongo_clean_ar.py , mongo_clean_status.py
=> ARGO-285 Use report uuid when cleaning data

status-computation/java/pom.xml
Currently we are generating only surefire reports. This pull requests adds the cobertura-magen-plugin in order to be able to generate cobertura coverage reports.
=> Adds support for cobertura coverage reports

status-computation/java/src/main/java/ar/AddGroupInfo.java, status-computation/java/src/main/java/ar/PickEndpoints.java, status-computation/java/src/main/java/status/PrepStatusDetails.java, status-computation/java/src/main/java/sync/EndpointGroups.java, status-computation/java/src/test/java/sync/EndpointGroupsTest.java, status-computation/pig/compute-ar.pig, status-computation/pig/compute-status.pig
Compute engine should be able to handle a service endpoint that belongs -at the same time- to multiple endpoint groups.
This feature requires refactoring in java udf classes and in pig scripts. Till now metric data rows were enriched with an endpoint_group field (retrieved by asking endpoint group topology mgr class based on hostname and service fields). The assumption was that each metric data row having a hostname and service info (service endpoint) corresponds to a unique endpoint group. Now the endpoint group mgr returns a list of endpoint groups that contain the endpoint. Then by having a crossproduct (X) of relevant metric data rows and endpoint group list, the needed (multiplied) metric data is produced
=> ARGO-327 attach list of endpoint groups for each endpoint

.travis.yml
travis enviroment doesn't target python 2.6 -- instead uses python 2.7 as a default. 
In order to target easily python 2.6 change travis environment from java to python-centric. This environment still comes with java 7 and mvn installed. 
Use coverage.py for coverage in python src
=> ARGO-316 - Target python 2.6 and add coverage

bin/upload_metric.py, doc/compute-job-configuration.md
Some tenants don't require a prefilter step while moving the metric data to hdfs. 
Whether a tenant requires prefiltering or not is specified in `/etc/ar-compute-engine.conf` in section `[job]`: 
If option `{tenant-name}_prefilter=/path/to/prefilter/script` __is present__ , tenant requires prefilter process.
In the `upload_metric.py` script:
- Read tenant configuration
- If {tenant-name}_prefilter` option is absent treat (copy) the original metric data file as a prefiltered result, to be transfered to hdfs
Update compute engine configuration documentation accordingly
=> ARGO-329 Handle optional prefiltering

ar-compute.spec
By default ```mvn package``` executes all the unit tests before
packaging. This commit changes this behaviour in order not to
run the unit tests
=> ARGO-326 Skips tests when packaging

status-computation/java/src/main/java/ops/CTimeline.java, status-computation/java/src/test/java/ops/CAggregatorTest.java
When going from lower levels of timelines to upper ones, we aggregate. (metrics -> endpoints -> services -> endpoint_groups -> upper groups etc...)
If during an aggregation, the candidate list contains only ONE timeline, then CE skips aggregation and passes the timeline to the upper level.
The problem is that optimization procedure call, happens only after an aggregation,  thus resulting in some cases in unoptimized timelines. Especially when: a site has a single service with a single endpoint containing only a single metric.
Java class that implements Continuous Timeline and Aggregion (`ops.CTimeline`)
- When aggregation call is skipped, due to single timeline presence, add call to optimize it
- Update relevant unittests
=> ARGO-332 Optimize single timelines

bin/upload_sync.py, conf/ar-compute-engine.conf.template
After the latest induced changes on the connectors (per customer configuration files) a change is needed in the compute engine with regard to the downtimes connector and how it should be called from within the CE framework. 
please review /cc @kaggis
=> ARGO-346 Modify downtimes calling method in upload_sync.py utility to read tenant-wise configuration.

bin/job_status_detail.py, status-computation/java/src/main/java/ar/GroupEndpointTimelines.java, status-computation/java/src/main/java/ar/PickEndpoints.java, status-computation/java/src/main/java/status/PrepStatusDetails.java, status-computation/java/src/main/java/sync/Recomputations.java, status-computation/java/src/test/java/ar/PickEndpointsTest.java, status-computation/java/src/test/java/sync/RecomputationsTest.java, status-computation/java/src/test/resources/ops/recomp.json, status-computation/pig/compute-ar.pig, status-computation/pig/compute-status.pig
Change CE to accept data from multiple monitoring engines ...thus multiple values in the `monitoring_host` avro field
Be able to exclude metric data for specific time periods for problematic monitoring engines (based again on `monitoring_host` field and `timestamp`)
Append extra information about excluding monitoring engines in the available recomputation schema
__Previous recomputation schema:__
```json
[{
"reason": "testing_compute_engine",
"start_time": "2013-12-08T12:03:44Z",
"end_time": "2013-12-10T12:03:44Z",
"exclude": [
"SITE-A",
"SITE-B"
],
"status": "running",
"timestamp": "2015-02-01 14:58:40"
}]
```
__Refactored recomputation schema:__
```json
[{
"reason": "testing_compute_engine",
"start_time": "2013-12-08T12:03:44Z",
"end_time": "2013-12-10T12:03:44Z",
"exclude": [
"SITE-A", …
```
=> ARGO-337 Handle metric data from multiple monitoring engines

status-computation/java/src/main/java/ar/FillMissing.java, status-computation/java/src/main/java/ar/UnwindServiceMetrics.java, status-computation/java/src/test/java/ar/FillMissingTest.java, status-computation/java/src/test/java/ar/UnwindServiceMetricsTest.java, status-computation/java/src/test/resources/ar/missing_endpoint.json, status-computation/java/src/test/resources/ar/missing_endpoint_full.json, status-computation/pig/compute-ar.pig, status-computation/pig/compute-status.pig
Based on given topology CE produces expected rows of hostname,service,metric. This set is compared with the received metric data and if combinations of hostname,service,metric are missing from the monitoring system they are filled in and added to the rest of the metric data. This enables CE to produce missing timelines for endpoints that are completely missing for long periods of time
=> ARGO-330 Fill Missing Endpoints when absent from metric data

.travis.yml, doc/flume_decode_interceptor.md, flume/decode_interceptor/pom.xml, flume/decode_interceptor/src/main/java/argo/flume/interceptor/DecodeInterceptor.java, flume/decode_interceptor/src/test/java/argo/flume/interceptor/DecodeInterceptorTest.java, flume/decode_interceptor/src/test/java/log4j.properties, flume/decode_interceptor/src/test/resources/event_body.json
When using ARGO Messaging API for ingestrion through flume, CE should use a flume interceptor to extract and decode the pure payload of the msgs received from the API. 
This Custom Flume interceptor is implemented as DecodeInterceptor Java class in a small maven project. 
The Interceptor purpose:
- Intecept the event (calling intercept() method)
- Extract json field "data"
- Base64 decode field's (data) value
- set event body to the decoded value
- Return the event
The maven project is implemented in the `./flume/decode_interceptor/' directory
=> ARGO-350 Add Flume Decode Interceptor

bin/poller_ar.py, bin/test_poller_ar.py
The `poller_ar.py` calls the `recompute.py` wrapper with an additional argument (`-j`) that is not required and actually produces an exception. The latter wrapper picks up the name of the report directly from querying the mongo datastore.
=> Fix in poller python script

bin/recompute.py, bin/recompute_test.py
This PR introduces two changes:
1. Removes a deprication warning emitted through python about the `update` function usage (see below)
2. Inserts the timestamp of the state change in the format expected by the Web API
C/p the deprication warning is the following:
```
/usr/libexec/ar-compute/bin/recompute.py:113: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
collection.update({'id': rec_id}, {'$set': {"status": status,"timestamp": timestamp} })
```
=> Change in mongo update call

conf/ar-compute-engine.conf.template
Description
Change default values for configuration variables `prefilter_clean` and `sync_clean` to `false`.
=> ARGO-196 prefilter_clean and sync_clean should be false by default

doc/argo-compute-engine/ingestion_dataflow.md, ingestion/flume/conf/flume-agent-metric-data.conf.template, ingestion/flume/conf/flume-agent-sync-data.conf.template, ingestion/hive/scripts/hive_tbl_downtimes.sql, ingestion/hive/scripts/hive_tbl_endpoint_groups.sql, ingestion/hive/scripts/hive_tbl_group_groups.sql, ingestion/hive/scripts/hive_tbl_metric_data.sql, ingestion/hive/scripts/hive_tbl_metric_profiles.sql, ingestion/hive/scripts/hive_tbl_weights.sql
Prepare CE dataflow to be able to accept metric data through Ingestion (using the ingestion API)
Add Documentation, configuration and script regarding ingestion of sync data in the compute engine
- metric_profiles
- group_groups
- group_endpoints
- downtimes
- weights
To be merged after PR: https://github.com/ARGOeu/argo-compute-engine/pull/169
=> ARGO-388 Ingestion of sync data

bin/upload_metric.py, bin/utils.py, bin/utils_test.py, conf/ar-compute-engine.conf.template
In tenants that doesn't use prefiltering retrieval of consumer data is hard coded to `/var/lib/consumer-...`
=> ARGO-455 Add consumers root path parameter. 

bin/job_ar.py, bin/job_status_detail.py, bin/mongo_clean_ar.py, status-computation/pig/compute-ar.pig, status-computation/pig/compute-status.pig
Mongodb result set (for a given collection, report and date) is cleared before hadoop computation begins. Until computation finished old results are thus missing from the datastore
=> ARGO-581 Use Update when storing results in mongo

status-computation/pig/compute-status.pig
`endpoint_group` field was ommited from the update status_metric procedure. The field was used in query for displaying status metric results
- Add endpoint_group field in update statement in compute_status pig script
=> ARGO-611 Add ommited endpoint_group field in update status_metrics

streaming/stream_hbase/metric_data.avsc, streaming/stream_hbase/pom.xml, streaming/stream_hbase/src/main/java/argoflink/ArgoStreamHbase.java, streaming/stream_hbase/src/main/resources/log4j.properties, streaming/stream_hbase/src/main/resources/schemas/metric_data.avsc
*To be merged after: https://github.com/ARGOeu/argo-compute-engine/pull/178
Add Hbase as destination in argo streaming pipeline
- Add two job subfolders in `/streaming` : `stream_hdfs`, `stream_hbase`
- Add HbaseOutputFormat impementation
- User WriteTo HbaseOutputFormat as a destination in stream pipeline
=> ARGO-599 Add Hbase destination to stream pipeline
